WICG/sanitizer-api

- README.md
This updates the explainer to be more in line with what we've discussed so far.
It updates the API to match what's been spec'ed in index.bs.
> Update explainer. Adapt to API proposal from spec.

- README.md
Consistent terminology (we use allowlist nearly everywhere).
> Consistent terminology

- README.md
Align the readme with current discussion.
* Remove string-to-string examples in favour of string-to-fragment.
* Remove pre-configured Sanitizers (in favour of a single, safe default).
> Rework examples in README.md

- index.bs
This specifies SantiizerInput, largely based on #22.
> Specify InputOptions.

- index.bs
This is the initial text, I envision to discuss the problems we are and aren't solving with this spec.
I'm honestly not sure whether we need references for things like mXSS, DOM clobbering and Script Gadgets, as this is non-normative, but can add if necessary.
> Initial text for Security Considerations

- security-questionnaire.md
> security questionnaire, first iteration

- deploy.sh
Follow-up to branch rename. #66
> Adapt branch name in deploy.sh

- index.bs
This fixed reference errors the bnikeshed tool reports.
> Fix reference errors.

- index.bs
This follows #92, which in turn follows earlier TAG feedback on the spec.
> Change config to be an attribute getter.

- index.bs
No idea how useful this is... I found this functionatliy in the bikeshed manual (https://tabatkins.github.io/bikeshed/#wpt-element), and its easy to do. I think the main drawback is that presently the test suite isn't super impressive, so I'm not sure how usefule this is.
wdyt?
> Link to WPT tests.

- index.bs
Human-readable explanation of the strings API, and why they are the way they are. Including exapmles and references.
> Explain string APIs.

- index.bs
Fix an omission in the current spec.
> Descirbe how element is created.

- index.bs
`blockAttributes` is not in the spec, it should be a `dropAttributes`.
> Fix `blockAttributes` to `dropAttributes` in sample code and nits

- explainer.md
This adds some examples to the explainer. I did my best to follow the current discussion, even though not all of the bits are finalized any may well change when actually specified.
> Explainer examples

- .pr-preview.json
Based on https://github.com/w3c/trusted-types/blob/main/.pr-preview.json
> Add .pr-preview.json file

- README.md
- explainer.md
> Remove unused Travis CI widget.

- index.bs
Overdue :)
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/pull/255.html" title="Last updated on Feb 5, 2025, 9:53 AM UTC (dd39db0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/255/8e8c366...dd39db0.html" title="Last updated on Feb 5, 2025, 9:53 AM UTC (dd39db0)">Diff</a>
> Adding more folks to acknowledgements

- index.bs
Fixes: #256
***
<a href="https://pr-preview.s3.amazonaws.com/otherdaniel/purification/pull/257.html" title="Last updated on Feb 18, 2025, 1:49 PM UTC (7de40ac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/257/2805e96...otherdaniel:7de40ac.html" title="Last updated on Feb 18, 2025, 1:49 PM UTC (7de40ac)">Diff</a>
> Expose Sanitizer only on Window, not on worker.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/evilpie/sanitizer-api/pull/263.html" title="Last updated on Mar 5, 2025, 8:46 AM UTC (0082fc8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/263/80dfa6f...evilpie:0082fc8.html" title="Last updated on Mar 5, 2025, 8:46 AM UTC (0082fc8)">Diff</a>
> Sort <base> in the "built-in navigating URL attributes list"

- builtins/safe-default-configuration.json
Result of re-running ./build.sh. This makes the effect of #266 visible.
***
<a href="https://pr-preview.s3.amazonaws.com/otherdaniel/purification/pull/270.html" title="Last updated on Mar 7, 2025, 1:43 PM UTC (e86869d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/270/7c587a6...otherdaniel:e86869d.html" title="Last updated on Mar 7, 2025, 1:43 PM UTC (e86869d)">Diff</a>
> rerun build.sh
