WICG/sanitizer-api

index.src.html

This should reflect where the spec is being maintained.
I expect this additional metadata will allow working auto-import into
https://github.com/mozilla/standards-positions/
Note that this changes the license information that is generated.

Add metadata appropriate for a WICG specification.

---

.travis.yml

travis fails with bikeshed requiring a python that isn't 2.7

upgrade python to unbreak travis ci

---

index.bs

Minor fixes:
- Use IDL constructor.
- Missing </ol> causes mis-indentation.

Minor fixes: IDL syntax + closing list.

---

README.md
index.bs

This PR intend to:
1. Change `toString` to `sanitizeToString`.
2. Change `toFragment` to `sanitize`.
3. Add `CreationOptions` attribute into `Sanitizer` interface.
4. Change the `SanitizerConfig`.

Change the function & attribute names Sanitizer interface and SanitizerConfig dictionary

---

index.bs

Follow-up from #37: If we think of the DocumentFragement-based API as the primary sanitizer API, maybe we shouldn't lead our motivating examples with the string version. This strips down the examples a bit, and re-writes them to use fragments instead of strings.

Remove string examples

---

index.bs

This removes a that are potentially useful, but so far were neither speced out nor discussed properly. These should be trivial to add back if we want to support them after all.
Additionally, removing the static methods fixes a bikeshed error about duplicate defintiions of "sanitizerToString".

Cleanup: Remove un-specced features.

---

README.md
index.bs

Specify behaviour of drop, block, and allow lists. This means to formalize the discussion at #33.
Features are:
1, Built-ins are handled first, and thus cannot be overriden.
2, Except dropping an element with all children is handled before built-in element blocking, which should allow us to emulate DOMPurify's KEEP_CONTENT.
(Assuming that the built-ins e.g. block <script> (but not its content), a user could then add <script> into the drop list, meaning that <script> and all children would be dropped.)
3. I've tried to translate this into spec-like algorithms language. First time, so... please look closely.
This would also obsolete #15.

Formalize drop lists (& friends)

---

index.bs

This change makes the spec compile without warnings with the bikeshed tool.
This defines all references (in a few places as placeholders), but otherwise doesn't mean to change the semantics. It also adds some exmaples.

Define all references; add examples.

---

index.bs

Formalize behaviour of custom elements by introducing an "allow custom elements" option.
This PR follows discussion in #17.

Specify behaviour of custom elements.

---

index.bs

This specifies handling of allow/blockAttributes, following discussion in #18.
I don't think we explcitily agreed on how to handle attributes in the SanitizerConfig. The goal here is to resolve #18, and specifically to
- allow(block specific element/attribute combinations. (E.g. <script src=.>, but not \<img src=.>)
- allow emulation of existing sanitizers (e.g. DOMPurify specifies attribtues independent of the element).

Specify allow/blockAttributes.

---

index.bs

This spells out a consequence of using the existing HTML parser machinery, that may not be obvious to someone unfamiliar with the specs.

Add note about input normalization.

---

index.bs

In repsonse to issue #58, introduce special case handling for certain elements. So far, only `template` is affected.

Introduce special-case handling.

---

index.bs

Editorial changes:
- Consistently use the same header markers, and close the header before the anchor tag.
- Consistently use 1. for numbering (to minimize diffs for changes).
- Properly define & link the spec methods.

Editorial changes: Header markers, numbering, method definitions.

---

index.bs

This implements spec feedback, that algorithms should be more explicit with the variables they use, and should use bikeshed's algorithm= annotations, which improves index generation and display.
This should be a purely editorial change and a semantic no-op.

Editorial changes: Use algorithm= annotations, and regularize "algorithm" language.

---

index.bs

This (partially) implements spec feedback that the long constant definitions are hard to read. This moves them into a (normative) appendix, and (non-normatively) references the scripts that builds those constants.

Editorial change: Move constants into appendix.

---

index.bs

This picks up comments from several sources, including our "spec mentor", the [TAG](https://github.com/w3ctag/design-reviews/issues/619#issuecomment-809700791), and issue #69. It provides an explanation where our defaults are coming from, and links those to the HTML spec, so that a reader can go back and forth to understand the issue.
Linking is, honestly, best effort since some elements/attributes don't have good link targets. Particularly the legacy / non-conforming ones don't seem to have a "nice" linkable definition in HTML.

Justify the built-ins.

---

index.bs

New feature: Allow introspection of Sanitizers' configuration. (#77)

Introspection of Sanitizer configs (and default config).

---

index.bs

Change all examples to .sanitize, except the one that motivates .sanitizeToString.
This is basically an "educational" change in that we'd prefer the use of .sanitize over .sanitizeToString, and don't want to water down that message by using .sanitizeToString as the default example throughout our spec.

Use .sanitize in examples by default.

---

resources/baseline-element-allow-list.json
resources/default-configuration.json
resources/defaults-derivation.html

The (non-normative) built-ins paragraph lists `<noscript>` as not allowable, but this wasn't actually reflected in the (normative) built-in constants in the spec. I think that was unintended, and this fixes it. (See also: #86)

Remove <noscript> from default & baseline.

---

index.bs

this came up during implementation/review and I think it would be useful to make explicit. Happy to incorporate it somewhere else or in a different form.
This is the best place I could find, but maybe you'll find a better section of the document :-)

explicit conversion of element names to lowercase

---

index.bs

The previous definition kept anything (unless dropped). That's unbecoming for a sanitizer, and this changes the algorithm to drop all nodes unless they're being kept. Text node's are kept by default, and Dcoument/DocumentFragments, but only if they're the root.

Clarification on how other node types work.

---

index.bs

This reverts commit f3f52ce95d9516f525c071a7f9f56c21205840be.
See discussion at https://github.com/WICG/sanitizer-api/issues/107.

Revert "Change config to be an attribute getter."

---

index.bs

Specify new string handling: Instead of DOMString being in SanitizerInput and sanitizeToString, we now have sanitizeFor and Element.SetInnerHTML.
This addresses discussion in #42 (and also #37). It does change the API substantially.
This will require a good bit of follow-on work, like changing examples in the readme & faq, etc.

New string handling.

---

index.bs

Not sure if this is the best solution, but it ought to fix a pretty embarrassing corner case in the current spec.

Specify that the parse context for string-based methods is checked against the baseline config.

---

index.bs

- Move WPT test references to the algorithm section (rather than framework)
- Expand the references.
- Move non-API helper functions out of the API section, so that it's easy to see whether all API functions have test coverage or not.

Expand & Move test references

---

index.bs

- Cleanup & fix several spec references.
- Cleanup numbering.
- Fix the no-lon ger-accurate summary to make sure this no longer entirely about strings.

Editorial cleanup.

---

index.bs

Re-word and reflect the changes from PR #90 in the algorithms and examples.

Normalize element names.

---

index.bs

Change Element.setHTML(DOMString, Sanitizer) to Element.setHTML(DOMString, {sanitizer: Sanitizer}).
This follows the consensus at #121.

Introduce Element.setHTML options dictionary.

---

index.bs

* Support SVG and MathML embedded content in Sanitizer API.
* Plus some cleanup in the spec, to support the main change.

SVG and MathML

---

index.bs

This fixes several examples for `setHTML`, by adapting them to the changes of #138, as reported in #143.

Fix setHTML examples to use options dictionary.

---

index.bs

Bikeshed issues a warning if a variable has not been defined, and we do not define |this|.
> WARNING: The following \<var>s were only used once in the document:
>   'this'
> If these are not typos, please add an ignore='' attribute to the \<var>.

nit: Remove bikeshed warning about single-use variable.

---

index.bs

(Merge the other pull request in 152 before this one)
Invoke the right 'replace' function when sanitize a documentfragment - fixes #156

Invoking the right 'replace' function when sanitizing a DocFragment

---

index.bs

Another followup to #158: Remove language that normalizes case or uses case-insensitive comparisons.
Also affects #145.

Remove case normalization.

---

index.bs

First step to resolving #147: Do not refer to elements by their interfaces in "funky elements" handling.

Refer to elements by namespace and local name

---

index.bs

Fix up two spec references, to silence bikeshed errors:
- |this| => [=this=]
- define a reference for "template contents"

Fix spec references: this and template contents.

---

index.bs

The "[=replace with=]" spec ref doesn't actually exist. Replace this with a combination of append and replace.

Properly define "block" action.

---

index.bs

Remove the current, prefix:name-based treatment of namespaces from the spec. The goal is to revert the spec to be HTML-only, so that we can then build up a new API along the lines of #181.

Remove current namespace wording from the current draft.

---

explainer.md

This adds additional examples to the explainer and largely reaches "feature parity" with the existing spec, but based on our current thinking.

Add more examples.

---

index.bs

This closes #209, by adding "__TO_BE_MERGED" to any methods already defined in HTML. The intent is that the reader can still identify which method we mean, but the tools won't get confused.

Avoid overloading HTML methods

---

index.bs

Minor edit just to make it clearer when upstreaming to HTML that you should keep the HTMLString type.

Update Unsafe methods to use HTMLString IDL type from Trusted Types

---

explainer.md
index.bs

This makes a configuration query-able, and should make it easy (or easier) to derive a new configuration from an existing one. In terms of spec & implementation, this leans heavily on the existing canonicalization.
----
This needs further discussion. We had discussed re-introducing a configuration object in order to expose the canonical configuration(s), but not how exactly that should look like. This proposes specific spec & explainer wording to focus the discussion.

Introduce a query-able Sanitizer (or config) object.

---

index.bs

Identifiers of an extended attribute need to be enclosed in parentheses in Web IDL: https://webidl.spec.whatwg.org/#dfn-extended-attribute

Fix `Exposed` statement in dfn of `Sanitizer` interface

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/lukewarlow/sanitizer-api/pull/223.html" title="Last updated on Apr 17, 2024, 9:38 AM UTC (909a215)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/223/abac6ed...lukewarlow:909a215.html" title="Last updated on Apr 17, 2024, 9:38 AM UTC (909a215)">Diff</a>

Fix some spec references

---

index.bs

Fix typos and grammar. No changes of substance.
Fixes #220. Following that bug, I ran the text through a spell checker and found a few more issues.
***
<a href="https://pr-preview.s3.amazonaws.com/otherdaniel/purification/pull/224.html" title="Last updated on Apr 18, 2024, 1:08 PM UTC (7f741f6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/224/6fe2555...otherdaniel:7f741f6.html" title="Last updated on Apr 18, 2024, 1:08 PM UTC (7f741f6)">Diff</a>

Various typos & grammar fixes.

---

index.bs

Remove refences to `.sanitize` and `.sanitizeFor`.
Update the text to reference the current API.
Fixes #213.
***
<a href="https://pr-preview.s3.amazonaws.com/otherdaniel/purification/pull/219.html" title="Last updated on Apr 17, 2024, 9:33 AM UTC (a556353)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/219/abac6ed...otherdaniel:a556353.html" title="Last updated on Apr 17, 2024, 9:33 AM UTC (a556353)">Diff</a>

Update Mutated XSS chapter to reference the current API.

---

index.bs

Apologies for the spec churn here but this updates the integration Trusted Types to use union types and a call out to the correct TT algorithm, replacing the old IDL integration.
***
<a href="https://pr-preview.s3.amazonaws.com/lukewarlow/sanitizer-api/pull/234.html" title="Last updated on Jun 24, 2024, 3:34 PM UTC (645d26c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/234/c8e529d...lukewarlow:645d26c.html" title="Last updated on Jun 24, 2024, 3:34 PM UTC (645d26c)">Diff</a>

Update unsafe methods to use new trusted types integration

---

index.bs

Element.innerHTML is defined in HTML, not DOM.
Fixes #232.
***
<a href="https://pr-preview.s3.amazonaws.com/otherdaniel/purification/pull/235.html" title="Last updated on Jun 25, 2024, 10:13 AM UTC (01593ff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/235/c8e529d...otherdaniel:01593ff.html" title="Last updated on Jun 25, 2024, 10:13 AM UTC (01593ff)">Diff</a>

Update reference to Element.innerHTML.

---

index.bs

Editorial hygiene: Resolve all bikeshed warnings, mainly by fixing up link syntax. There should be no change in substance.
This removes WPT tests (for now), since they currently mismatch the updated spec and thus generate non-resolvable and non-actionable warnings.
***
<a href="https://pr-preview.s3.amazonaws.com/otherdaniel/purification/pull/239.html" title="Last updated on Sep 12, 2024, 12:53 PM UTC (a81448e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/239/d6e50d0...otherdaniel:a81448e.html" title="Last updated on Sep 12, 2024, 12:53 PM UTC (a81448e)">Diff</a>

Editorial hygiene: No bikeshed warnings.

---

explainer.md
index.bs

[This isn't quite ready yet. Using a PR for tool support and discussion.]
This re-writes the config logic, based on discussions in the recent meetings, and with the intent to address issues #228, #229, and #233.
The corner stones are:
- The Sanitizer (and thus its config) become mutable. It has methods to add stuff to  any of the allow or deny lists.
- The actual config processing is now defined in terms of those methods.
- There is only one "safe-ify" operation, and it gets called once (for safe methods). This is the only different between safe and unsafe versions.
- (Well, this is only a half-truth. The handling of javascript:-navigation URLs remains an odd-ball that is magically different between "safe" and "unsafe" versions.)
- The configs have an "other" setting, which allows them to …

Modify-able config.

---

index.bs

SetHTMLOptions's "sanitizer" key can now also contain an enum SanitizerPresets, which has only one member, "default". Which, it turns out, is the default value. This is now the only way to invoke the defaults. An empty dictionary would then
be a Sanitizer which allows anything. (Minus the "removeUnsafe" content, when used with a "safe" method.)
This follows discussion at the 2024-11-27 meeting.
The explainer still needs updaing.
***
<a href="https://pr-preview.s3.amazonaws.com/otherdaniel/purification/pull/243.html" title="Last updated on Dec 11, 2024, 4:03 PM UTC (f267f67)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/243/7e2f127...otherdaniel:f267f67.html" title="Last updated on Dec 11, 2024, 4:03 PM UTC (f267f67)">Diff</a>

Update the default handling

---

index.bs

The list was missing `iframe src` and I also sorted the list
***
<a href="https://pr-preview.s3.amazonaws.com/mozfreddyb/sanitizer-api/pull/247.html" title="Last updated on Dec 19, 2024, 12:08 PM UTC (be6c893)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/247/4497de3...mozfreddyb:be6c893.html" title="Last updated on Dec 19, 2024, 12:08 PM UTC (be6c893)">Diff</a>

Sort built-in navigating URL attributes list and add iframe src

---

index.bs

Run the basic URL parser to determine whether a URL is a `javascript:` URL.
Fixes: #246
***
<a href="https://pr-preview.s3.amazonaws.com/otherdaniel/purification/pull/248.html" title="Last updated on Jan 10, 2025, 12:53 PM UTC (2c33101)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/248/0e58018...otherdaniel:2c33101.html" title="Last updated on Jan 10, 2025, 12:53 PM UTC (2c33101)">Diff</a>

Run URL parser to determine URL protocol.

---

index.bs

- Add SVG <a href> & <a xlink:href> to list of javascript:-attributes.
- Add a list for SVG animations.
- Minor edits when using those lists.
***
<a href="https://pr-preview.s3.amazonaws.com/otherdaniel/purification/pull/212.html" title="Last updated on Jan 10, 2025, 2:32 PM UTC (7134494)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/212/3604c34...otherdaniel:7134494.html" title="Last updated on Jan 10, 2025, 2:32 PM UTC (7134494)">Diff</a>

Update "javascript:" handling; esp. SVG animation and MathML href.

---

index.bs

Give explicit defaults to SanitizerConfig.comments and SanitizerConfig.dataAttributes.
This fixes one of the issues in #249.
***
<a href="https://pr-preview.s3.amazonaws.com/otherdaniel/purification/pull/254.html" title="Last updated on Jan 31, 2025, 10:35 AM UTC (15cf1fc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/254/8e8c366...otherdaniel:15cf1fc.html" title="Last updated on Jan 31, 2025, 10:35 AM UTC (15cf1fc)">Diff</a>

Defaults for boolean SanitizerConfig items

---

builtins/safe-default-configuration.py

The `dir` attribute is in both MathML and HTML globals. The current script will just add it twice. This adds a check for an equal item that already exists.
Fixes: #264

Check for dupes when generating the default config.

---

index.bs

Fixes #274
***
<a href="https://pr-preview.s3.amazonaws.com/evilpie/sanitizer-api/pull/275.html" title="Last updated on Mar 19, 2025, 11:25 AM UTC (5e2c250)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/275/445eca6...evilpie:5e2c250.html" title="Last updated on Mar 19, 2025, 11:25 AM UTC (5e2c250)">Diff</a>

Immediately continue in sanitize core after removing or replacing a node

---

index.bs

Fixes #261
Currently, using a replaceWithChildrenElements list together with an elements list does not really work.
Because we first remove all elements that are not in the elements list, which means there is nothing to replace,
because it's impossible for an element to be in both lists.
Example:
```
setHTML("<p><i>hi<i></p>") { elements: ["i"], replaceWithChildrenElements: ["p"] })
```
Before this would just remove the `<p>` element. After this change they are replaced with their allowed child elements
(i.e. `<i>`).
Depends on #275
***
<a href="https://pr-preview.s3.amazonaws.com/evilpie/sanitizer-api/pull/277.html" title="Last updated on Mar 19, 2025, 3:53 PM UTC (49b26b0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/277/8265187...evilpie:49b26b0.html" …

Handle replaceWithChildrenElements before the elements allowlist in sanitize core

---

index.bs

It turns out that "fragment parsing algorithm steps" and "HTML fragment parsing algorithm" are related, but not the same reference. This fixes the confusion. Also add "HTML fragment parsing algorithm" as an explicit anchor, since the
reference isn't exported.
Fixes: #272
***
<a href="https://pr-preview.s3.amazonaws.com/otherdaniel/purification/pull/276.html" title="Last updated on Mar 19, 2025, 3:22 PM UTC (2784290)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/276/445eca6...otherdaniel:2784290.html" title="Last updated on Mar 19, 2025, 3:22 PM UTC (2784290)">Diff</a>

Fix reference to HTML fragment parsing algorithm.

---

index.bs

Fixes #260
Previously it treated just |sanitizer| as a SanitizerConfig instead of a Sanitizer.
Also replaces |this| with |sanitizer|.
***
<a href="https://pr-preview.s3.amazonaws.com/evilpie/sanitizer-api/pull/279.html" title="Last updated on Mar 21, 2025, 9:32 AM UTC (353a177)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/279/58bbb39...evilpie:353a177.html" title="Last updated on Mar 21, 2025, 9:32 AM UTC (353a177)">Diff</a>

Set a configuration must correctly refer to sanitizer's config

---

builtins/safe-default-configuration.json
builtins/safe-default-configuration.py
index.bs

1. Changes the parameter of **_set a configuration_** from *safe* to the inverted *allowCommentsAndDataAttributes*.
2. From the constructor don't allow comment/attributes when creating a `"default"` Sanitizer.
Fixes #273
***
<a href="https://pr-preview.s3.amazonaws.com/evilpie/sanitizer-api/pull/284.html" title="Last updated on Apr 2, 2025, 9:58 AM UTC (f94ccc1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/284/3cd0ca8...evilpie:f94ccc1.html" title="Last updated on Apr 2, 2025, 9:58 AM UTC (f94ccc1)">Diff</a>

Don't allow comments and data-attributes when creating a default Sanitizer

---

builtins/safe-default-configuration.json
builtins/safe-default-configuration.py

The safe-default-configuration.txt mirrors the HTML spec, and contains a few attributes both as global attributes as well as per-element attributes (because those elements assign specific semantics to them). Copying both of them into our default config is redundant, and leaves to surprising behaviour if users remove the global attributes (and would still find per-element attributes).
This follows discussion in #271. We remove any dupes from the builtins; but leave the algorithms themselves alone.
This is implemented by more comprehensive dupe-filtering in the script that generates the builtins.
Fixes: #271
***
<a href="https://pr-preview.s3.amazonaws.com/otherdaniel/purification/pull/278.html" title="Last updated on Mar 20, 2025, 12:09 PM UTC (c6d555f)">Preview</a> | <a …

Dedupe defaults

---

index.bs

This does the following:
- When canonicalizing SanitizerElementWithAttributes we don't remove duplicates in the local attributes/removeAttributes anymore.
- In the Sanitizer constructor we now throw for duplicates.
- In allowElement we now remove all duplicate attributes.
Fixes #306.
***
<a href="https://pr-preview.s3.amazonaws.com/evilpie/sanitizer-api/pull/309.html" title="Last updated on Sep 22, 2025, 10:59 AM UTC (ed2fa93)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/309/51f78b0...evilpie:ed2fa93.html" title="Last updated on Sep 22, 2025, 10:59 AM UTC (ed2fa93)">Diff</a>

Handle duplicate local attributes

---

index.bs

Local attributes/removeAttributes list are only supported with a global elements list. Otherwise we should just ignore the unsatisfiable request. I also added an optional warning, but we can remove that if it is unwanted.
Fixes #304
***
<a href="https://pr-preview.s3.amazonaws.com/evilpie/sanitizer-api/pull/312.html" title="Last updated on Sep 22, 2025, 10:37 AM UTC (e54c6fa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/312/51f78b0...evilpie:e54c6fa.html" title="Last updated on Sep 22, 2025, 10:37 AM UTC (e54c6fa)">Diff</a>

Do nothing for allowElement with local attributes and a global removeElements list

---

index.bs

We should always remove duplicates from `element["attributes"]` in **allow an element**. (Regression from #309)
***
<a href="https://pr-preview.s3.amazonaws.com/evilpie/sanitizer-api/pull/319.html" title="Last updated on Sep 24, 2025, 12:05 PM UTC (0eccfda)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/319/86da938...evilpie:0eccfda.html" title="Last updated on Sep 24, 2025, 12:05 PM UTC (0eccfda)">Diff</a>

Fix the wrong nesting of remove duplicates in allowElement()

---

index.bs

Regression from #316. Somehow, I thought we were in a loop.
***
<a href="https://pr-preview.s3.amazonaws.com/evilpie/sanitizer-api/pull/326.html" title="Last updated on Sep 26, 2025, 2:18 PM UTC (0db70b4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/sanitizer-api/326/a1c5410...evilpie:0db70b4.html" title="Last updated on Sep 26, 2025, 2:18 PM UTC (0db70b4)">Diff</a>

Return result instead of wrongly using continue.
